BusTour/BusTour/Controllers/CitiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BusTour;

namespace BusTour.Controllers
{
    public class CitiesController : Controller
    {
        private Bus_TourEntities1 db = new Bus_TourEntities1();

        // GET: Cities
        public ActionResult Index()
        {
            try
            {
                var city = db.City.Include(p => p.Country1);
                return View(city.ToList());
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        // GET: Cities/Details/5
        public ActionResult Details(int? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                City city = db.City.Find(id);
                if (city == null)
                {
                    return HttpNotFound();
                }
                return View(city);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        // GET: Cities/Create
        public ActionResult Create()
        {
            try
            {
                ViewBag.Country_Id = new SelectList(db.Country, "Country_Id", "Country_Name");
                return View();
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        // POST: Cities/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "City_Id,City_name,Country_Id,City_short_descr")] City city, HttpPostedFileBase upload)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (upload != null)
                    {
                        string fileName = System.IO.Path.GetFileName(upload.FileName);
                        upload.SaveAs(Server.MapPath("~/Image/" + fileName));
                        db.City.Add(city);
                        city.City_Image_Name = fileName;
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                }
                ViewBag.Country_Id = new SelectList(db.Country, "Country_Id", "Country_Name", city.Country_Id);
                return View(city);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        // GET: Cities/Edit/5
        public ActionResult Edit(int? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                City city = db.City.Find(id);
                if (city == null)
                {
                    return HttpNotFound();
                }
                ViewBag.Country_Id = new SelectList(db.Country, "Country_Id", "Country_Name");
                return View(city);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        // POST: Cities/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "City_Id,City_name,Country,City_short_descr")] City city, HttpPostedFileBase upload)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (upload != null)
                    {
                        string fileName = System.IO.Path.GetFileName(upload.FileName);
                        upload.SaveAs(Server.MapPath("~/Image/" + fileName));
                        db.Entry(city).State = EntityState.Modified;
                        city.City_Image_Name = fileName;
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                }
                ViewBag.Country_Id = new SelectList(db.Country, "Country_Id", "Country_Name");
                return View(city);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        // GET: Cities/Delete/5
        public ActionResult Delete(int? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                City city = db.City.Find(id);
                if (city == null)
                {
                    return HttpNotFound();
                }
                return View(city);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        // POST: Cities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                City city = db.City.Find(id);
                db.City.Remove(city);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        protected override void Dispose(bool disposing)
        {
            try
            {
                if (disposing)
                {
                    db.Dispose();
                }
                base.Dispose(disposing);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
    }
}

BusTour/BusTour/Views/Cities/Create.cshtml
@model BusTour.City

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 style="uk-text-large" class="uk-margin-top">Create City</h2>


@using (Html.BeginForm("Create", "Cities", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>City</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.City_name, "City", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Country_Id, "Country", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Country_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Country_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City_short_descr, "Short Description", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City_short_descr, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City_short_descr, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>

        <input type="file" name="upload" /><br />
        <input type="submit" value="Load" />
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", new { }, htmlAttributes: new { @class = "uk-button uk-button-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BusTour/BusTour/Views/Cities/Delete.cshtml
@model BusTour.City

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 style="uk-text-large" class="uk-margin-top">Delete City</h2>

<h3 style="uk-text-capitalize">Are you sure you want to delete this?</h3>
<div>
    <h4>City</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("City")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City_name)
        </dd>

        <dt>
            @Html.DisplayName("Country")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country1.Country_Name)
        </dd>

        <dt>
            @Html.DisplayName("Short Description")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City_short_descr)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="uk-button uk-button-primary" /> 
        @Html.ActionLink("Back to List", "Index", new { }, htmlAttributes: new { @class = "uk-button uk-button-primary" })
    </div>
    }
</div>

BusTour/BusTour/Views/Cities/Details.cshtml
@model BusTour.City

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 style="uk-text-large" class="uk-margin-top">City Details</h2>

<div>
    <h4>City</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("City_name")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City_name)
        </dd>

        <dt>
            @Html.DisplayName("Country")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country1.Country_Name)
        </dd>

        <dt>
            @Html.DisplayName("Short Description")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City_short_descr)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.City_Id }) |
    @Html.ActionLink("Back to List", "Index", new { }, htmlAttributes: new { @class = "uk-button uk-button-primary" })
</p>

BusTour/BusTour/Views/Cities/Edit.cshtml
@model BusTour.City

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 style="uk-text-large" class="uk-margin-top">City Edit</h2>


@using (Html.BeginForm("Edit", "Cities", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>City</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.City_Id)

        <div class="form-group">
            @Html.LabelFor(model => model.City_name, "City", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Country1.Country_Id, "Country", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Country_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Country1.Country_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City_short_descr, "Short Description", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City_short_descr, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City_short_descr, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
        <input type="file" name="upload" /><br />
        <input type="submit" value="Load" />
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", new { }, htmlAttributes: new { @class = "uk-button uk-button-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BusTour/BusTour/Views/Cities/Index.cshtml
@model IEnumerable<BusTour.City>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2 style="uk-text-large" class="uk-margin-top">Cities</h2>

<p class="link">
    @Html.ActionLink("Create New", "Create", new { }, htmlAttributes: new { @class = "uk-button uk-button-primary" })
</p>

<div class="uk-block uk-padding-vertical-remove">
    @foreach (var item in Model)
    {
        <div class="uk-block uk-margin-remove uk-padding-top-remove">
            <div class="uk-panel uk-panel-box uk-panel-box-primary">
                <img src="/Image/@item.City_Image_Name" class=" uk-float-left uk-margin-right"  style="width:400px; height:200px;box-shadow:0 0 10px rgba(0,0,0,0.5);" />
                <h3 class="uk-panel-title">
                    <i class="uk-icon-building"></i>
                    @Html.DisplayFor(modelItem => item.City_name) 
                </h3>
                <br />
                @Html.DisplayFor(modelItem => item.Country1.Country_Name)
                <br />
                @Html.DisplayFor(modelItem => item.City_short_descr)
                <br />
                @Html.ActionLink("Delete", "Delete", new { id = item.City_Id }, htmlAttributes: new { @class = "uk-button uk-button-primary uk-float-right", @style= "position:absolute; right: 33px; bottom: 30px; width: 100x; height: 25px;" })
                @Html.ActionLink("Details", "Details", new { id = item.City_Id }, htmlAttributes: new { @class = "uk-button uk-button-primary uk-float-right", @style = "position:absolute; right: 100px; bottom: 30px;" })
                @Html.ActionLink("Edit", "Edit", new { id = item.City_Id }, htmlAttributes: new { @class = "uk-button uk-button-primary uk-float-right", @style = "position:absolute;right:170px;bottom:30px;height:25px;" })
            </div>
        </div>
    }
</div>