BusTour/BusTour/Controllers/PlacesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BusTour;

namespace BusTour.Controllers
{
    public class PlacesController : Controller
    {
        private Bus_TourEntities1 db = new Bus_TourEntities1();

        // GET: Places
        public ActionResult Index()
        {
            try
            {
                var place = db.Place.Include(p => p.Place_Type).Include(p => p.City);
                return View(place.ToList());
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        // GET: Places/Details/5
        public ActionResult Details(int? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Place place = db.Place.Find(id);
                if (place == null)
                {
                    return HttpNotFound();
                }
                return View(place);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        // GET: Places/Create
        public ActionResult Create()
        {
            try
            {
                ViewBag.Type_Place_Id = new SelectList(db.Place_Type, "Type_Place_Id", "Place_Type1");
                ViewBag.City_Id = new SelectList(db.City, "City_Id", "City_name");
                return View();
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        // POST: Places/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Place_Id,City_Id,Type_Place_Id,Place_short_descr")] Place place, HttpPostedFileBase upload)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (upload != null)
                    {
                        string fileName = System.IO.Path.GetFileName(upload.FileName);
                        upload.SaveAs(Server.MapPath("~/Image/" + fileName));
                        place.Place_Image_Name = fileName;
                        db.Place.Add(place);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                }
                ViewBag.Type_Place_Id = new SelectList(db.Place_Type, "Type_Place_Id", "Place_Type1", place.Type_Place_Id);
                return View(place);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        // GET: Places/Edit/5
        public ActionResult Edit(int? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Place place = db.Place.Find(id);
                if (place == null)
                {
                    return HttpNotFound();
                }
                ViewBag.Type_Place_Id = new SelectList(db.Place_Type, "Type_Place_Id", "Place_Type1", place.Type_Place_Id);
                ViewBag.City_Id = new SelectList(db.City, "City_Id", "City_name", place.City_Id);
                return View(place);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        // POST: Places/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Place_Id,City_Id,Type_Place_Id,Place_short_descr")] Place place, HttpPostedFileBase upload)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (upload != null)
                    {
                        string fileName = System.IO.Path.GetFileName(upload.FileName);
                        upload.SaveAs(Server.MapPath("~/Image/" + fileName));
                        db.Entry(place).State = EntityState.Modified;
                        place.Place_Image_Name = fileName;
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                }
                ViewBag.Type_Place_Id = new SelectList(db.Place_Type, "Type_Place_Id", "Place_Type1", place.Type_Place_Id);
                return View(place);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        // GET: Places/Delete/5
        public ActionResult Delete(int? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Place place = db.Place.Find(id);
                if (place == null)
                {
                    return HttpNotFound();
                }
                return View(place);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        // POST: Places/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                Place place = db.Place.Find(id);
                db.Place.Remove(place);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        protected override void Dispose(bool disposing)
        {
            try
            {
                if (disposing)
                {
                    db.Dispose();
                }
                base.Dispose(disposing);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
    }
}

BusTour/BusTour/Views/Places/Create.cshtml
@model BusTour.Place

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 style="uk-text-large" class="uk-margin-top">Create</h2>

@using (Html.BeginForm("Create", "Places", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Place</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.City_Id, "City_Id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("City_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.City_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type_Place_Id, "Type_Place_Id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Type_Place_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Type_Place_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Place_short_descr, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Place_short_descr, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Place_short_descr, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
        <input type="file" name="upload" /><br />
        <input type="submit" value="Load" />
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BusTour/BusTour/Views/Places/Delete.cshtml
@model BusTour.Place

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 style="uk-text-large" class="uk-margin-top">Delete Place</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Place</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("City")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City_Id)
        </dd>

        <dt>
            @Html.DisplayName("Place Short Description")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Place_short_descr)
        </dd>

        <dt>
            @Html.DisplayName("Type of Place")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Place_Type.Place_Type1)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="uk-button uk-button-primary" />
        @Html.ActionLink("Back to List", "Index", new { }, htmlAttributes: new { @class = "uk-button uk-button-primary" })
    </div>
    }
</div>

BusTour/BusTour/Views/Places/Details.cshtml
@model BusTour.Place

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 style="uk-text-large" class="uk-margin-top">Place Details</h2>

<div>
    <h4>Place</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("City")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City_Id)
        </dd>

        <dt>
            @Html.DisplayName("Place Short Description")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Place_short_descr)
        </dd>

        <dt>
            @Html.DisplayName("Place Type")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Place_Type.Place_Type1)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Place_Id }) |
    @Html.ActionLink("Back to List", "Index", new { }, htmlAttributes: new { @class = "uk-button uk-button-primary" })
</p>

BusTour/BusTour/Views/Places/Edit.cshtml
@model BusTour.Place

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 style="uk-text-large" class="uk-margin-top">Edit Place</h2>


@using (Html.BeginForm("Edit", "Places", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Place</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Place_Id)

        <div class="form-group">
            @Html.LabelFor(model => model.City_Id, "City", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City_Id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type_Place_Id, "Type Place", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Type_Place_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Type_Place_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Place_short_descr, "Place Short Description", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Place_short_descr, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Place_short_descr, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
        <input type="file" name="upload" /><br />
        <input type="submit" value="Load" />
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", new { }, htmlAttributes: new { @class = "uk-button uk-button-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BusTour/BusTour/Views/Places/Index.cshtml
@model IEnumerable<BusTour.Place>

@{
    ViewBag.Title = "Places";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 style="uk-text-large" class="uk-margin-top">Places</h2>

<p class="link">
    @Html.ActionLink("Create New", "Create", new { }, htmlAttributes: new { @class = "uk-button uk-button-primary" })
</p>

<div class="uk-block">
    @foreach (var item in Model)
    {
        <div class="uk-block uk-block ">
            <div class="uk-panel uk-panel-box uk-panel-box-primary">
                <img src="/Image/@item.Place_Image_Name" class=" uk-float-left uk-margin-right" style="width:400px; height:200px;box-shadow:0 0 10px rgba(0,0,0,0.5);" />
                <h3 class="uk-panel-title">
                    <i class="uk-icon-university">
                    </i>  @Html.DisplayFor(modelItem => item.City.City_name)
                </h3>

                @Html.DisplayFor(modelItem => item.Place_Type.Place_Type1)
                <br />
                @Html.DisplayFor(modelItem => item.Place_short_descr)

                <br />

                @Html.ActionLink("Delete", "Delete", new { id = item.Place_Id }, htmlAttributes: new { @class = "uk-button uk-button-primary", @style= "position:absolute;right:33px;bottom:30px;width:100x;height:25px;" })
                @Html.ActionLink("Details", "Details", new { id = item.Place_Id }, htmlAttributes: new { @class = "uk-button uk-button-primary", @style="position:absolute; right: 100px; bottom: 30px;" })
                @Html.ActionLink("Edit", "Edit", new { id = item.Place_Id }, htmlAttributes: new { @class = "uk-button uk-button-primary", @style= "position:absolute;right:170px;bottom:30px;height:25px;" })

            </div>
        </div>
    }
</div>