BusTour/BusTour/Controllers/ToursController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BusTour;
using BusTour.Models;
using MailKit.Net.Smtp;
using MimeKit;

namespace BusTour.Controllers
{
    public class ToursController : Controller
    {
        private Bus_TourEntities1 db = new Bus_TourEntities1();

        // GET: Tours
        public ActionResult Index()
        {
            try
            {
                var tour = db.Tour.Include(t => t.City).Include(t => t.Route);
                return View(tour.ToList());
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        // GET: Tours/Details/5
        public ActionResult Details(int? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Tour tour = db.Tour.Find(id);
                Route route = db.Route.Find(tour.Route_Id);

                if (tour == null)
                {
                    return HttpNotFound();
                }

                ViewBag.Places = db.Place_in_the_route
                .Where(x => x.Route_Id == route.Route_Id)
                .OrderBy(x => x.Number_of_Day);

                List<int> Places_ids = new List<int>();
                foreach (var p in ViewBag.Places)
                {
                    Places_ids.Add(p.Place_Id);
                }

                ViewBag.Places_info = db.Place.Where(
                x => Places_ids.Contains(x.Place_Id));
                return View(tour);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        // GET: Tours/Create
        public ActionResult Create()
        {
            try
            {
                ViewBag.City_Id = new SelectList(db.City, "City_Id", "City_name");
                ViewBag.Route_Id = new SelectList(db.Route, "Route_Id", "Route_Description");
                return View();
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        // POST: Tours/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Tour_Id,Route_Id,City_Id,Tour_Cost,Tour_Duration,Date_of_Depature,Tour_Name,Tour_Image")] Tour tour, HttpPostedFileBase upload)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (upload != null)
                    {
                        string fileName = System.IO.Path.GetFileName(upload.FileName);
                        upload.SaveAs(Server.MapPath("~/Image/" + fileName));
                        db.Tour.Add(tour);
                        tour.Tour_Image_Name = "/Image/" + fileName;
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                }

                ViewBag.City_Id = new SelectList(db.City, "City_Id", "City_name", tour.City_Id);
                ViewBag.Route_Id = new SelectList(db.Route, "Route_Id", "Route_Description", tour.Route_Id);
                return View(tour);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }


        // GET: Tours/Edit/5
        public ActionResult Edit(int? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Tour tour = db.Tour.Find(id);
                if (tour == null)
                {
                    return HttpNotFound();
                }
                ViewBag.City_Id = new SelectList(db.City, "City_Id", "City_name", tour.City_Id);
                ViewBag.Route_Id = new SelectList(db.Route, "Route_Id", "Route_Description", tour.Route_Id);
                return View(tour);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        // POST: Tours/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Tour_Id,Route_Id,City_Id,Tour_Cost,Tour_Duration,Date_of_Depature,Tour_Name,Tour_Image")] Tour tour, HttpPostedFileBase upload)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (upload != null)
                    {
                        string fileName = System.IO.Path.GetFileName(upload.FileName);
                        upload.SaveAs(Server.MapPath("~/Image/" + fileName));
                        db.Entry(tour).State = EntityState.Modified;
                        tour.Tour_Image_Name = "/Image/" + fileName;
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                }
                ViewBag.City_Id = new SelectList(db.City, "City_Id", "City_name", tour.City_Id);
                ViewBag.Route_Id = new SelectList(db.Route, "Route_Id", "Route_Description", tour.Route_Id);
                return View(tour);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        // GET: Tours/Delete/5
        public ActionResult Delete(int? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Tour tour = db.Tour.Find(id);
                if (tour == null)
                {
                    return HttpNotFound();
                }
                return View(tour);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        // POST: Tours/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                Tour tour = db.Tour.Find(id);
                db.Tour.Remove(tour);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        protected override void Dispose(bool disposing)
        {
            try
            {
                if (disposing)
                {
                    db.Dispose();
                }
                base.Dispose(disposing);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
    }
}

BusTour/BusTour/Views/Tours/Create.cshtml
@model BusTour.Tour

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 style="uk-text-large" class="uk-margin-top">Create Tour</h2>


@using (Html.BeginForm("Create", "Tours", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Tour</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Tour_Name, "Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tour_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tour_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Route_Id, "Route", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Route_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Route_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City_Id, "City", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("City_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.City_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tour_Cost, "Cost", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tour_Cost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tour_Cost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tour_Duration, "Tour Duration", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tour_Duration, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tour_Duration, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date_of_Depature, "Date of Departure", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date_of_Depature, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                @Html.ValidationMessageFor(model => model.Date_of_Depature, "", new { @class = "text-danger" })
            </div>
            <br />
        </div>
        <input type="file" name="upload" /><br />
        <input type="submit" value="Load" />

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", new { }, htmlAttributes: new { @class = "uk-button uk-button-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BusTour/BusTour/Views/Tours/Delete.cshtml
@model BusTour.Tour

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 style="uk-text-large" class="uk-margin-top">Delete Tour</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Tour</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Tour Name")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tour_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tour_Cost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tour_Cost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tour_Duration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tour_Duration)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date_of_Depature)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date_of_Depature)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.City.City_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City.City_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Route.Route_Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Route.Route_Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="uk-button uk-button-primary" />
        @Html.ActionLink("Back to List", "Index", new { }, htmlAttributes: new { @class = "uk-button uk-button-primary" })
    </div>
    }
</div>

BusTour/BusTour/Views/Tours/Details.cshtml
@model BusTour.Tour

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<script src="~/Scripts/bootstrap.min.js"></script>

<h2 style="uk-text-large" class="uk-margin-top">Tour Details</h2>
<div class="uk-block uk-block-muted" style="background-color:white; width: 100%; height: 40em;">
    <img src="@Model.Tour_Image_Name" class=" uk-float-left" style="position:absolute; left: 0px; top: 0px; box-shadow:0 0 20px rgba(0,0,0,0.5);" width="800" height="350" />
    <div class="uk-block uk-block-default" style="background-color:white;position:absolute;left:0px;bottom:0px; width:800px; height:8em">
        <p class="uk-text-center uk-margin-top-remove uk-text-primary" style="font-size:18px;position:absolute;top:20%;left:40%;"> @Model.Tour_Name</p>
        <p style="font-size:14px; position:absolute;top:60%;left:40%;">@Model.Route.Route_Description</p>
    </div>
    <button type="button" class="uk-button uk-button-primary" data-toggle="modal" data-target="#myModal" style="position:absolute; right: 0px; bottom: 0px; width: 29.8%; height: 7em; font-size:16px;">
        Submit application
    </button>
    <dl class="dl-horizontal uk-float-right uk-text-left" style="position:absolute;right:60px;top:10px;">
        <dt class="uk-text-left">
            @Html.DisplayName("Name")
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Tour_Name)
        </dd>
        <dt class="uk-text-left">
            @Html.DisplayName("Route Description")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Route.Route_Description)
        </dd>
        <dt class="uk-text-left">
            @Html.DisplayName("Cost")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tour_Cost)
        </dd>

        <dt class="uk-text-left">
            @Html.DisplayName("Duration")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tour_Duration)
        </dd>

        <dt class="uk-text-left">
            @Html.DisplayName("Date of Depature")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date_of_Depature)
        </dd>

        <dt class="uk-text-left">
            @Html.DisplayName("City of Departure")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City.City_name)
        </dd>
    </dl>
</div>

<div>
    <br />
    <br />
</div>


<div class="uk-block uk-block-muted">
    <table class="table">
        <tr>
            <th>
                @Html.DisplayName("Number of Day in Route")
            </th>
            <th>
                @Html.DisplayName("Day Description")
            </th>
        </tr>

        @foreach (var p in ViewBag.Places)
        {
            <tr>
                <td>
                    Day @p.Number_of_Day
                    <p> @Model.Date_of_Depature.Value.AddDays(@p.Number_of_Day).ToString("dd/MM/yyyy")</p>
                </td>
                <td>
                    @p.Day_Description
                </td>

            </tr>
        }

    </table>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Tour_Id }, htmlAttributes: new { @class = "uk-button uk-button-primary" })
    @Html.ActionLink("Back to List", "Index", new { }, htmlAttributes: new { @class = "uk-button uk-button-primary" })
</p>

<!-- Modal -->
<div class="modal fade" id="myModal" role="dialog" aria-labelledby="exampleModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">
                    Travel request
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="myForm">

                    <label style="font-size:large;">@Model.Tour_Name</label>
                    <br />
                    <text>@Model.Route.Route_Description</text>
                    <br />
                    <text style="color:gray" class="uk-margin-bottom">Date: @Model.Date_of_Depature.Value.ToString("dd/MM/yyyy")</text>
                    <br />
                    <br />
                    <label for="exampleInputEmail1">Your Name</label>
                    @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })

                    <label for="exampleInputEmail1">Email address</label>
                    @Html.TextBoxFor(model => model.Email, new { @class = "form-control" })

                    <label for="exampleInputEmail1">Phone number</label>
                    @Html.TextBoxFor(model => model.Number, new { @class = "form-control" })
                    <small id="emailHelp" class="form-text text-muted">We'll never share your email and phone number with anyone else.</small>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <input type="reset" value="Submit" class="btn btn-success" id="btnSubmit" />
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="myModaltwo" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">
                    Travel request
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p> Thank you!</p>
                <br/>
                <p>Have a good day!</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Ok</button>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $("#btnSubmit").click(function () {
            var myformdata = $("#myForm").serialize();
            $.ajax({
                type: "POST",
                url: "/Home/Feedback",
                data: myformdata,
                success: function () {
                    $("#myModal").modal("hide");
                    $("#myModal .close").click();
                    $("#myModaltwo").modal("show");
                }
            })
        })
    })
</script>

BusTour/BusTour/Views/Tours/Edit.cshtml
@model BusTour.Tour

@{
    /**/

    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 style="uk-text-large" class="uk-margin-top">Edit Tour</h2>


@using (Html.BeginForm("Edit", "Tours", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="panel-body">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Tour_Id)
        <div class="form-group">
            @Html.LabelFor(model => model.Tour_Name, "Tour Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tour_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tour_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Route_Id, "Route", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Route_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Route_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City_Id, "City", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("City_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.City_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tour_Cost, "Cost", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tour_Cost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tour_Cost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tour_Duration, "Duration", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tour_Duration, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tour_Duration, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date_of_Depature, "Date of Departure", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date_of_Depature, new { htmlAttributes = new { @class = "form-control ", @type = "date" } })
                @Html.ValidationMessageFor(model => model.Date_of_Depature, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <br />
        <input type="file" name="upload" /><br />
        <input type="submit" value="Load" />
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", new { }, htmlAttributes: new { @class = "uk-button uk-button-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BusTour/BusTour/Views/Tours/Index.cshtml
@model IEnumerable<BusTour.Tour>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 style="uk-text-large" class="uk-margin-top">Tours</h2>

<p class="link">
    @Html.ActionLink("Create New", "Create", new { }, htmlAttributes: new { @class = "uk-button uk-button-primary" })
</p>

<div class="uk-container">

    @foreach (var item in Model)
    {
        <div class="uk-block">
            <div class="uk-panel uk-panel-box uk-panel-box-primary">
                <img src="@item.Tour_Image_Name" class=" uk-float-left uk-margin-right" style="width:400px; height:200px;box-shadow:0 0 10px rgba(0,0,0,0.5);" />
                <h3 class="uk-panel-title">
                    <i class="uk-icon-bus">
                    </i> @Html.Label("Name") : @Html.DisplayFor(modelItem => item.Tour_Name)

                    @Html.ActionLink("More..", "Details", new { id = item.Tour_Id }, htmlAttributes: new { @class = "uk-button uk-button-primary uk-float-right" })
                </h3>
                
                @Html.DisplayFor(modelItem => item.Route.Route_Description)
                <br />
                <br />
                @Html.Label("Date of Departure") : @Html.DisplayFor(modelItem => item.Date_of_Depature)
                <br />

                @Html.Label("Tour Duration") : @Html.DisplayFor(modelItem => item.Tour_Duration)
                <br />

                @Html.Label("Cost") :@Html.DisplayFor(modelItem => item.Tour_Cost) <i class="uk-icon-dollar"></i>
                <br />

                @Html.Label("Departure City") :@Html.DisplayFor(modelItem => item.City.City_name)
                <br />

                @Html.ActionLink("Edit", "Edit", new { id = item.Tour_Id }, htmlAttributes: new { @class = "uk-button uk-button-primary", @style = "position:absolute;right:100px;bottom:20px;height:25px;" })
                @Html.ActionLink("Delete", "Delete", new { id = item.Tour_Id }, htmlAttributes: new { @class = "uk-button uk-button-primary", @style = "position:absolute;right:20px;bottom:20px;height:25px;" })

            </div>

        </div>
    }
</div>

BusTour/BusTour/Views/Tours/SendEmail.cshtml
@model BusTour.Tour
<div>
<p>Hi</p>
</div>