BusTour/BusTour/Controllers/Place_in_the_routeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BusTour;

namespace BusTour.Controllers
{
    public class Place_in_the_routeController : Controller
    {
        private Bus_TourEntities1 db = new Bus_TourEntities1();

        // GET: Place_in_the_route
        public ActionResult Index()
        {
            try
            {
                var place_in_the_route = db.Place_in_the_route.Include(p => p.Place).Include(p => p.Route);
                return View(place_in_the_route.ToList());
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        // GET: Place_in_the_route/Details/5
        public ActionResult Details(int? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Place_in_the_route place_in_the_route = db.Place_in_the_route.Find(id);
                if (place_in_the_route == null)
                {
                    return HttpNotFound();
                }
                return View(place_in_the_route);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        // GET: Place_in_the_route/Create
        public ActionResult Create()
        {
            try
            {
                ViewBag.Place_Id = new SelectList(db.Place, "Place_Id", "Place_short_descr");
                ViewBag.Route_Id = new SelectList(db.Route, "Route_Id", "Route_Description");
                return View();
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        // POST: Place_in_the_route/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Place_in_the_route_Id,Place_Id,Route_Id,Number_of_Day,Day_Description")] Place_in_the_route place_in_the_route)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Place_in_the_route.Add(place_in_the_route);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                ViewBag.Place_Id = new SelectList(db.Place, "Place_Id", "Place_short_descr", place_in_the_route.Place_Id);
                ViewBag.Route_Id = new SelectList(db.Route, "Route_Id", "Route_Description", place_in_the_route.Route_Id);
                return View(place_in_the_route);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        // GET: Place_in_the_route/Edit/5
        public ActionResult Edit(int? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Place_in_the_route place_in_the_route = db.Place_in_the_route.Find(id);
                if (place_in_the_route == null)
                {
                    return HttpNotFound();
                }
                ViewBag.Place_Id = new SelectList(db.Place, "Place_Id", "Place_short_descr", place_in_the_route.Place_Id);
                ViewBag.Route_Id = new SelectList(db.Route, "Route_Id", "Route_Description", place_in_the_route.Route_Id);
                return View(place_in_the_route);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        // POST: Place_in_the_route/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Place_in_the_route_Id,Place_Id,Route_Id,Number_of_Day,Day_Description")] Place_in_the_route place_in_the_route)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(place_in_the_route).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                ViewBag.Place_Id = new SelectList(db.Place, "Place_Id", "Place_short_descr", place_in_the_route.Place_Id);
                ViewBag.Route_Id = new SelectList(db.Route, "Route_Id", "Route_Description", place_in_the_route.Route_Id);
                return View(place_in_the_route);
            }

            catch (Exception ex)
            {
                throw ex;
            }
        }

        // GET: Place_in_the_route/Delete/5
        public ActionResult Delete(int? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Place_in_the_route place_in_the_route = db.Place_in_the_route.Find(id);
                if (place_in_the_route == null)
                {
                    return HttpNotFound();
                }
                return View(place_in_the_route);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        // POST: Place_in_the_route/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                Place_in_the_route place_in_the_route = db.Place_in_the_route.Find(id);
                db.Place_in_the_route.Remove(place_in_the_route);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        protected override void Dispose(bool disposing)
        {
            try
            {
                if (disposing)
                {
                    db.Dispose();
                }
                base.Dispose(disposing);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
    }
}

BusTour/BusTour/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <link rel="stylesheet" href="css/uikit.min.css" />
        <script src="js/uikit.min.js"></script>
        <script src="js/uikit-icons.min.js"></script>
    <title>Tours</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
   
</head>
<body style="background-image:url(/Image/main3.jpg); background-size:auto">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Tours", "Index", "Tours", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav nav-pills">
                    <li>@Html.ActionLink("Cities", "Index", "Cities", new { area = "" }, new { @class = "navbar-brand" })</li>
                    <li>@Html.ActionLink("Places", "Index", "Places", new { area = "" }, new { @class = "navbar-brand" })</li>
                    <li>@Html.ActionLink("Routes", "Index", "Routes", new { area = "" }, new { @class = "navbar-brand" })</li>
                    <li>@Html.ActionLink("Place in Route", "Index", "Place_in_the_route", new { area = "" }, new { @class = "navbar-brand" })</li>
                    <li>@Html.ActionLink("About Program", "About", "Home", new { area = "" }, new { @class = "navbar-brand" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "navbar-brand" })</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>